# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

target 'loyalty-demo' do
  pod 'Alamofire', '~> 2.0.2'
  pod 'MeshbluKit', '~> 1.5.1'
  pod 'MeshbluBeaconKit', '~> 2.5.0'
end

target 'loyalty-demoTests' do

end