# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'loyalty-demo' do
  pod "MeshbluBeaconKit"
  pod "MeshbluKit"
end

target 'loyalty-demoTests' do

end

